name: Release

on: [workflow_dispatch]

jobs:
  release:
    name: Create Release
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: install dependencies
        run: |
          sh .github/install-dependencies.sh
      - name: build
        run: |
          sh .github/build.sh
      - name: build debian
        run: |
          sh .github/build_debian_pkg.sh
      - name: Release
        id: create_release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            /assets/*